# Generated by Django 4.0.4 on 2022-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Описание')),
                ('published', models.CharField(max_length=4, verbose_name='Год издания')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
