# Generated by Django 4.0.4 on 2022-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(max_length=4, verbose_name='Рік видання'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
    ]
