# Generated by Django 4.0.4 on 2022-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Показувати'),
        ),
    ]
