# Generated by Django 4.0.4 on 2022-07-14 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_book_options_alter_book_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown author', max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(default='2022', max_length=4, verbose_name='Рік видання'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(default='Text about the book', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='The title of the book', max_length=50, verbose_name='Назва'),
        ),
    ]
